;;; atlas-slice.el --- Dynamic org-mode registry buffer for Atlas entities -*- lexical-binding: t -*-

;; Copyright (C) 2025
;; Author: @tangrammer + LLMs

;;; Commentary:
;;
;; atlas-slice creates on-demand org-mode buffers assembled from the live
;; registry via CIDER.  Unlike atlas-lens-mode (which overlays an existing
;; source file), atlas-slice generates a dedicated buffer seeded from a query.
;;
;; Each entity is rendered as an org heading with a prose body generated by
;; atlas.ide.narrative on the Clojure side.  The buffer is read-only org-mode;
;; use C-x C-q to unlock for editing.
;;
;; Entry points:
;;   `atlas-slice-entity'  — entity + optional direct deps (by dev-id)
;;   `atlas-slice-aspect'  — all entities carrying an aspect keyword
;;   `atlas-slice'         — interactive dispatcher (entity / aspect)
;;
;; Inside a slice buffer:
;;   g / C-c C-l r   — refresh (re-fetch from REPL)
;;   i               — inspect entity at point (:semantic card in bottom window)
;;   s               — grep for register! call of entity at point
;;   q               — bury buffer
;;
;; Requires an active CIDER connection and atlas.ide.narrative on the classpath.

;;; Code:

(require 'atlas-core)
(require 'atlas-render)

;;; Buffer-local state

(defvar-local atlas-slice--seed-type nil
  "How this buffer was seeded: `:entity' or `:aspect'.")

(defvar-local atlas-slice--seed-arg nil
  "The seed argument: a dev-id string or aspect keyword string.")

(defvar-local atlas-slice--depth 0
  "Dep expansion depth for `:entity' seed.
0 = entity only; 1 = entity + direct deps.")

(defvar-local atlas-slice--entities-cache nil
  "Cached narrative context maps from last fetch.")

;;; Candidate cache (shared across all slice buffers, 30s TTL)

(defvar atlas-slice--candidate-cache nil
  "Cached (timestamp dev-id-list aspect-list) for completing-read.
Refreshed when older than `atlas-slice--candidate-ttl' seconds.")

(defconst atlas-slice--candidate-ttl 30
  "Seconds before the candidate cache is considered stale.")

(defun atlas-slice--fetch-all-dev-ids ()
  "Return sorted list of all dev-id strings from the live registry."
  (let* ((expr "(do (require '[atlas.registry :as registry])
                    (sort (mapv str (keys @registry/dev-id-index))))")
         (result (atlas--eval expr)))
    (cond
     ((vectorp result) (sort (append result nil) #'string<))
     ((listp result)   (sort result #'string<))
     (t                nil))))

(defun atlas-slice--fetch-all-aspects ()
  "Return sorted list of semantic aspect keyword strings from the live registry.
Excludes dotted namespaces (e.g. :some.ns.deep/thing) which are entity-internal
spec keys, not architectural aspects intended for slice queries."
  (let* ((expr "(do (require '[atlas.registry :as registry])
                    (->> (keys @registry/dev-id-index)
                         (mapcat #(registry/declared-aspects %))
                         distinct
                         (remove #(clojure.string/includes? (or (namespace %) \"\") \".\"))
                         sort
                         (mapv str)))")
         (result (atlas--eval expr)))
    (cond
     ((vectorp result) (append result nil))
     ((listp result)   result)
     (t                nil))))

(defun atlas-slice--candidates ()
  "Return (dev-ids aspects), fetching from REPL or using the cache."
  (unless (cider-connected-p)
    (user-error "Atlas Slice: REPL unavailable — connect CIDER first"))
  (let* ((now    (float-time))
         (cached atlas-slice--candidate-cache))
    (if (and cached (< (- now (car cached)) atlas-slice--candidate-ttl))
        (cdr cached)
      (message "Atlas Slice: fetching candidates…")
      (let* ((dev-ids (atlas-slice--fetch-all-dev-ids))
             (aspects (atlas-slice--fetch-all-aspects))
             (pair    (list dev-ids aspects)))
        (setq atlas-slice--candidate-cache (cons now pair))
        pair))))

(defun atlas-slice--invalidate-cache ()
  "Clear the candidate cache so the next command re-fetches from the REPL."
  (interactive)
  (setq atlas-slice--candidate-cache nil)
  (message "Atlas Slice: candidate cache cleared"))

;;; REPL fetch helpers

(defun atlas-slice--dev-ids-for-entity (dev-id depth)
  "Return list of dev-id strings: DEV-ID plus deps up to DEPTH hops.
Uses atlas.ontology/deps-for via the CIDER REPL."
  (if (= depth 0)
      (list dev-id)
    (let* ((expr (format
                  "(do (require '[atlas.ontology :as ont])
                       (let [dev-id %s
                             dep-ids (ont/deps-for dev-id)]
                         (mapv str (cons dev-id dep-ids))))"
                  dev-id))
           (result (atlas--eval expr)))
      (cond
       ((vectorp result) (append result nil))
       ((listp result)   result)
       (t                (list dev-id))))))

(defun atlas-slice--dev-ids-for-aspect (aspect)
  "Return list of dev-id strings for all entities carrying ASPECT keyword.
Uses atlas.registry/declared-aspects via the CIDER REPL."
  (let* ((expr (format
                "(do (require '[atlas.registry :as registry])
                     (mapv str
                       (->> (keys @registry/dev-id-index)
                            (filter #(contains? (registry/declared-aspects %%) %s))
                            (remove nil?))))"
                aspect))
         (result (atlas--eval expr)))
    (cond
     ((vectorp result) (append result nil))
     ((listp result)   result)
     (t                nil))))

(defun atlas-slice--fetch-entities (dev-ids)
  "Fetch narrative context maps for DEV-IDS via CIDER.
Calls atlas.ide.narrative/narrative-contexts.
Returns hash-table of dev-id → narrative context map, or nil."
  (when dev-ids
    (let ((ids-str (mapconcat #'identity dev-ids " ")))
      (let ((result (atlas--eval
                     (format "(do (require '[atlas.ide.narrative])
                                  (atlas.ide.narrative/narrative-contexts [%s]))"
                             ids-str))))
        (or result (make-hash-table :test 'equal))))))

(defun atlas-slice--topo-sort (dev-ids)
  "Return DEV-IDS topologically sorted via the live registry (deps first).
Only sorts within the given set — entities not in the list are ignored.
Falls back to the original order on error."
  (when dev-ids
    (let* ((ids-str (mapconcat #'identity dev-ids " "))
           (result  (atlas--eval
                     (format
                      "(do (require '[atlas.ontology :as ont])
                           (let [ids     [%s]
                                 id-set  (set ids)
                                 dep-map (into {} (map (fn [id] [id (filter id-set (ont/deps-for id))]) ids))
                                 sorted  (atom [])
                                 visited (atom #{})]
                             (letfn [(visit [id]
                                       (when-not (@visited id)
                                         (swap! visited conj id)
                                         (doseq [dep (get dep-map id [])] (visit dep))
                                         (swap! sorted conj id)))]
                               (doseq [id ids] (visit id)))
                             (mapv str @sorted)))"
                      ids-str))))
      (cond
       ((vectorp result) (append result nil))
       ((listp result)   result)
       (t                dev-ids)))))

;;; Org buffer rendering

(defun atlas-slice--summary-section (dev-ids entities)
  "Return an org `* Summary' section string for the slice."
  (let ((type-counts (make-hash-table :test 'equal)))
    (dolist (dev-id-str dev-ids)
      (let* ((info (atlas-render--lookup-entity entities dev-id-str))
             (type (when info
                     (atlas-render--resolve-narrative-value "entity-type" info))))
        (when (and type (not (string-empty-p type)))
          (puthash type (1+ (gethash type type-counts 0)) type-counts))))
    (let (pairs)
      (maphash (lambda (k v) (push (cons k v) pairs)) type-counts)
      (setq pairs (sort pairs (lambda (a b) (> (cdr a) (cdr b)))))
      (concat "* Summary\n\n"
              (format "%d %s\n\n" (length dev-ids)
                      (if (= 1 (length dev-ids)) "entity" "entities"))
              (mapconcat (lambda (p) (format "- %d × =%s=\n" (cdr p) (car p)))
                         pairs "")
              "\n"))))

(defun atlas-slice--org-entry (dev-id-str info)
  "Return an org-mode section string for one entity."
  (let* ((props (seq-filter (lambda (p) (not (string-empty-p (cdr p))))
                             (atlas-render--org-properties info)))
         (tags  (atlas-render--org-tags info))
         (body  (atlas-render--org-body info)))
    (concat (format "* %s%s\n" dev-id-str tags)
            (when props
              (concat ":PROPERTIES:\n"
                      (mapconcat (lambda (p) (format ":%s: %s\n" (car p) (cdr p)))
                                 props "")
                      ":END:\n"))
            "\n"
            body
            "\n\n")))

(defun atlas-slice--render (buf dev-ids entities seed-desc)
  "Populate BUF as an org-mode document for DEV-IDS (already topo-sorted)."
  (with-current-buffer buf
    (let ((inhibit-read-only t))
      (erase-buffer)
      (insert (format "#+TITLE: atlas-slice: %s\n#+DATE: %s\n#+OPTIONS: toc:nil num:nil\n#+STARTUP: overview\n\n"
                      seed-desc (format-time-string "%Y-%m-%d")))
      (insert (atlas-slice--summary-section dev-ids entities))
      (dolist (dev-id-str dev-ids)
        (let ((info (atlas-render--lookup-entity entities dev-id-str)))
          (when info
            (insert (atlas-slice--org-entry dev-id-str info)))))
      (goto-char (point-min))
      (when (fboundp 'org-overview)
        (org-overview)))))

;;; Commands

(defun atlas-slice-refresh ()
  "Re-fetch from the REPL and re-render the current slice buffer."
  (interactive)
  (if (not (cider-connected-p))
      (message "Atlas Slice: REPL unavailable — connect CIDER first")
    (let* ((seed-type atlas-slice--seed-type)
           (seed-arg  atlas-slice--seed-arg)
           (depth     atlas-slice--depth)
           (dev-ids   (cond
                       ((eq seed-type :entity)
                        (atlas-slice--dev-ids-for-entity seed-arg depth))
                       ((eq seed-type :aspect)
                        (atlas-slice--dev-ids-for-aspect seed-arg))
                       (t nil))))
      (if (null dev-ids)
          (message "Atlas Slice: no entities found for %s" seed-arg)
        (let* ((sorted-ids (or (atlas-slice--topo-sort dev-ids) dev-ids))
               (entities   (atlas-slice--fetch-entities sorted-ids)))
          (setq atlas-slice--entities-cache entities)
          (atlas-slice--render (current-buffer) sorted-ids entities seed-arg)
          (message "Atlas Slice: %s · %d entities"
                   seed-arg (length sorted-ids)))))))

;;; Compact inspect

(defun atlas-slice--fetch-entity-info (dev-id-str)
  "Fetch entity info for a single DEV-ID-STR via CIDER (for :semantic card)."
  (let ((result (atlas--eval
                 (format "(do (require '[atlas.ide :as ide]) (ide/entities-info [%s]))"
                         dev-id-str))))
    (or result (make-hash-table :test 'equal))))

(defun atlas-slice-inspect-at-point ()
  "Show a compact :semantic card for the entity at the current org heading.
Displays in a small window at the bottom; press q to close it."
  (interactive)
  (unless (cider-connected-p)
    (user-error "Atlas Slice: REPL unavailable — connect CIDER first"))
  (let* ((heading (save-excursion
                    (org-back-to-heading t)
                    (org-get-heading t t t t)))
         (dev-id  (string-trim heading))
         (entities (atlas-slice--fetch-entity-info dev-id))
         (info     (atlas-render--lookup-entity entities dev-id)))
    (if (null info)
        (message "Atlas Slice: no registry info for %s" dev-id)
      (let* ((card (atlas-render-form info :semantic))
             (buf  (get-buffer-create "*atlas-inspect*")))
        (with-current-buffer buf
          (let ((inhibit-read-only t))
            (erase-buffer)
            (insert card)
            (goto-char (point-min))
            (special-mode)
            (local-set-key (kbd "q") #'quit-window)))
        (display-buffer buf
                        '(display-buffer-at-bottom
                          (window-height . fit-window-to-buffer)))))))

;;; Jump to source

(defun atlas-slice-jump-to-source ()
  "Grep for the register! call of the entity at the current org heading.
Reads the dev-id from the heading text (tags are stripped automatically)."
  (interactive)
  (let* ((heading  (save-excursion
                     (org-back-to-heading t)
                     (org-get-heading t t t t)))
         (dev-id   (string-trim heading))
         (kw       (if (string-prefix-p ":" dev-id)
                       dev-id
                     (concat ":" dev-id)))
         (root     (or (when (fboundp 'project-root)
                         (ignore-errors
                           (project-root (project-current))))
                       default-directory)))
    (grep (format "grep -r -n --include='*.clj' --include='*.cljc' %s %s"
                  (shell-quote-argument kw)
                  (shell-quote-argument (expand-file-name root))))))

;;; Major mode

(defvar atlas-slice-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-l r") #'atlas-slice-refresh)
    (define-key map (kbd "g")         #'atlas-slice-refresh)
    (define-key map (kbd "i")         #'atlas-slice-inspect-at-point)
    (define-key map (kbd "s")         #'atlas-slice-jump-to-source)
    (define-key map (kbd "q")         #'quit-window)
    map)
  "Keymap for `atlas-slice-mode'.")

(define-derived-mode atlas-slice-mode org-mode "Atlas-Slice"
  "Major mode for Atlas slice buffers.
Org-mode document assembled from the live registry via CIDER.
Entities are topologically sorted (deps first) and tagged by type/domain/intent.
Starts folded — TAB to expand any heading.

\\{atlas-slice-mode-map}")

;;; Entry points

(defun atlas-slice--open-buffer (buf-name seed-type seed-arg depth)
  "Open (or reuse) the slice buffer named BUF-NAME with the given seed."
  (let* ((new-buf-p (not (get-buffer buf-name)))
         (buf       (get-buffer-create buf-name)))
    (when new-buf-p
      (with-current-buffer buf (atlas-slice-mode)))
    (with-current-buffer buf
      (setq atlas-slice--seed-type seed-type
            atlas-slice--seed-arg  seed-arg
            atlas-slice--depth     depth))
    (switch-to-buffer buf)
    (atlas-slice-refresh)))

(defun atlas-slice-entity (dev-id &optional depth)
  "Open an Atlas slice buffer for DEV-ID.
Prompts with a completion dropdown of all registered dev-ids.
With a numeric prefix argument N, include direct deps (depth N; default 0)."
  (interactive
   (let* ((candidates (car (atlas-slice--candidates)))
          (choice     (completing-read "Entity dev-id: " candidates nil nil ":"))
          (d          (if current-prefix-arg
                          (prefix-numeric-value current-prefix-arg)
                        0)))
     (list choice d)))
  (atlas-slice--open-buffer (format "*atlas: %s*" dev-id) :entity dev-id (or depth 0)))

(defun atlas-slice-aspect (aspect)
  "Open an Atlas slice buffer for all entities carrying ASPECT.
Prompts with a completion dropdown of all declared aspects."
  (interactive
   (let* ((candidates (cadr (atlas-slice--candidates)))
          (choice     (completing-read "Aspect: " candidates nil nil ":")))
     (list choice)))
  (atlas-slice--open-buffer (format "*atlas: %s*" aspect) :aspect aspect nil))

;;;###autoload
(defun atlas-slice ()
  "Open an Atlas slice buffer — interactive dispatcher.
First choose entity or aspect, then pick from a completion dropdown.
With a numeric prefix argument N, entity slices expand N hops of deps."
  (interactive)
  (let ((seed-type (completing-read "Slice by: " '("entity" "aspect") nil t)))
    (pcase seed-type
      ("entity"  (call-interactively #'atlas-slice-entity))
      ("aspect"  (call-interactively #'atlas-slice-aspect)))))

(provide 'atlas-slice)
;;; atlas-slice.el ends here
