;;; atlas-business.el --- Business semantics for Atlas IDE support -*- lexical-binding: t -*-

;; Copyright (C) 2025
;; Author: @tangrammer + LLMs

;;; Commentary:
;;
;; Business semantics commands for Atlas Emacs integration:
;; - List business entities (patterns, constraints, failure modes, etc.)
;; - Business entity info
;; - Find implementations of business aspects

;;; Code:

(require 'atlas-core)
(require 'atlas-display)
(require 'atlas-completion)

;;;###autoload
(defun atlas-business-list-entities ()
  "List all business-layer entities grouped by type."
  (interactive)
  (atlas--invalidate-cache)
  (let* ((entities (atlas--eval-safe "(list-business-entities)" nil))
         (buf (atlas--buffer "business-entities")))
    (with-current-buffer buf
      (setq atlas--last-command #'atlas-business-list-entities)
      (atlas--insert-header "Business Semantics")
      (let ((patterns (atlas--to-list (atlas--get entities 'business/patterns)))
            (constraints (atlas--to-list (atlas--get entities 'business/constraints)))
            (failures (atlas--to-list (atlas--get entities 'business/failure-modes)))
            (values (atlas--to-list (atlas--get entities 'business/values)))
            (roles (atlas--to-list (atlas--get entities 'business/roles)))
            (experiences (atlas--to-list (atlas--get entities 'business/experiences))))
        (when (> (length patterns) 0)
          (atlas--insert-subheader (format "Patterns (%d)" (length patterns)))
          (dolist (p patterns)
            (insert "  ")
            (atlas--insert-business-entity p)
            (insert "\n"))
          (insert "\n"))
        (when (> (length constraints) 0)
          (atlas--insert-subheader (format "Constraints (%d)" (length constraints)))
          (dolist (c constraints)
            (insert "  ")
            (atlas--insert-business-entity c)
            (insert "\n"))
          (insert "\n"))
        (when (> (length failures) 0)
          (atlas--insert-subheader (format "Failure Modes (%d)" (length failures)))
          (dolist (f failures)
            (insert "  ")
            (atlas--insert-business-entity f)
            (insert "\n"))
          (insert "\n"))
        (when (> (length values) 0)
          (atlas--insert-subheader (format "Value Propositions (%d)" (length values)))
          (dolist (v values)
            (insert "  ")
            (atlas--insert-business-entity v)
            (insert "\n"))
          (insert "\n"))
        (when (> (length roles) 0)
          (atlas--insert-subheader (format "User Roles (%d)" (length roles)))
          (dolist (r roles)
            (insert "  ")
            (atlas--insert-business-entity r)
            (insert "\n"))
          (insert "\n"))
        (when (> (length experiences) 0)
          (atlas--insert-subheader (format "User Experiences (%d)" (length experiences)))
          (dolist (e experiences)
            (insert "  ")
            (atlas--insert-business-entity e)
            (insert "\n"))
          (insert "\n")))
      (goto-char (point-min))
      (read-only-mode 1))
    (pop-to-buffer buf)))

;;;###autoload
(defun atlas-business-info (entity)
  "Show detailed business semantics info for ENTITY."
  (interactive
   (list (atlas--completing-read-entity "Business entity: ")))
  (let* ((entity-kw (atlas--to-keyword entity))
         (info (atlas--eval-safe (format "(business-entity-info %s)" entity-kw)))
         (buf (atlas--buffer (format "business:%s" entity))))
    (with-current-buffer buf
      (setq atlas--last-command (lambda () (atlas-business-info entity)))
      (atlas--insert-header (format "Business: %s" entity))
      (if (not info)
          (insert "  (no info available)\n")
        (atlas--format-business-info info)
        (let ((impls (atlas--to-list (atlas--get info 'business/implements-in))))
          (when (and impls (> (length impls) 0))
            (atlas--insert-subheader "Implemented In")
            (dolist (impl impls)
              (insert "  ")
              (atlas--insert-entity impl)
              (insert "\n"))
            (insert "\n"))))
      (goto-char (point-min))
      (read-only-mode 1))
    (pop-to-buffer buf)))

;;;###autoload
(defun atlas-business-implementations (business-aspect)
  "Show all technical entities implementing BUSINESS-ASPECT."
  (interactive
   (list (atlas--completing-read-aspect "Business aspect: ")))
  (let* ((aspect-kw (atlas--to-keyword business-aspect))
         (entities (atlas--eval-safe (format "(entities-implementing %s)" aspect-kw) []))
         (buf (atlas--buffer (format "impl:%s" business-aspect))))
    (with-current-buffer buf
      (setq atlas--last-command (lambda () (atlas-business-implementations business-aspect)))
      (atlas--insert-header (format "Entities implementing %s" business-aspect))
      (let ((entities-list (atlas--to-list entities)))
        (if (and entities-list (> (length entities-list) 0))
            (dolist (entity entities-list)
              (insert "  ")
              (atlas--insert-entity entity)
              (insert "\n"))
          (insert "  (no implementations found)\n")))
      (goto-char (point-min))
      (read-only-mode 1))
    (pop-to-buffer buf)))

;;;###autoload
(defun atlas-business-aspects-of (entity)
  "Show all business aspects applied to technical ENTITY."
  (interactive
   (list (atlas--completing-read-entity "Entity: ")))
  (let* ((entity-kw (atlas--to-keyword entity))
         (business (atlas--eval-safe (format "(business-aspects-of %s)" entity-kw) {}))
         (buf (atlas--buffer (format "business-of:%s" entity))))
    (with-current-buffer buf
      (setq atlas--last-command (lambda () (atlas-business-aspects-of entity)))
      (atlas--insert-header (format "Business aspects of %s" entity))
      (let ((patterns (atlas--to-list (atlas--get business 'business/patterns)))
            (constraints (atlas--to-list (atlas--get business 'business/constraints)))
            (failures (atlas--to-list (atlas--get business 'business/failure-modes)))
            (values (atlas--to-list (atlas--get business 'business/values)))
            (roles (atlas--to-list (atlas--get business 'business/roles)))
            (experiences (atlas--to-list (atlas--get business 'business/experiences))))
        (if (and (= 0 (length patterns)) (= 0 (length constraints))
                 (= 0 (length failures)) (= 0 (length values))
                 (= 0 (length roles)) (= 0 (length experiences)))
            (insert "  (no business aspects)\n")
          (when (> (length patterns) 0)
            (atlas--insert-subheader "Patterns")
            (dolist (p patterns) (insert "  ") (atlas--insert-aspect p) (insert "\n"))
            (insert "\n"))
          (when (> (length constraints) 0)
            (atlas--insert-subheader "Constraints")
            (dolist (c constraints) (insert "  ") (atlas--insert-aspect c) (insert "\n"))
            (insert "\n"))
          (when (> (length failures) 0)
            (atlas--insert-subheader "Failure Modes")
            (dolist (f failures) (insert "  ") (atlas--insert-aspect f) (insert "\n"))
            (insert "\n"))
          (when (> (length values) 0)
            (atlas--insert-subheader "Values")
            (dolist (v values) (insert "  ") (atlas--insert-aspect v) (insert "\n"))
            (insert "\n"))
          (when (> (length roles) 0)
            (atlas--insert-subheader "Roles")
            (dolist (r roles) (insert "  ") (atlas--insert-aspect r) (insert "\n"))
            (insert "\n"))
          (when (> (length experiences) 0)
            (atlas--insert-subheader "Experiences")
            (dolist (e experiences) (insert "  ") (atlas--insert-aspect e) (insert "\n"))
            (insert "\n"))))
      (goto-char (point-min))
      (read-only-mode 1))
    (pop-to-buffer buf)))

(provide 'atlas-business)
;;; atlas-business.el ends here
